### ISSUE TITLE
[META] Documenting the new Logos

### ISSUE THREAD

**Issue by jeertmans** [maciejhirsz/logos#292]
Hello all,

As already mentioned by many people, or very recently in https://github.com/maciejhirsz/logos/issues/291#issuecomment-1502137879, a major weakness of Logos is its documentation. While documenting code can be long and tedious, I think it leads to better stability over time (because examples can be tested with `cargo test`) and will also benefit a lot of people.

Also, more people will be able to understand how Logos works, then you are likely to attract more contributors (I think).

I'm not a Logos guru, but I use it quite often, and I documented many of my open source projects, so I propose the following ideas to improve Logo's documentation:

- [x] Add the following entries in `logos/Cargo.toml` https://github.com/maciejhirsz/logos/pull/300
```toml
[package.metadata.docs.rs]
all-features = true
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]
```
and probably something like this in `logos/src/lib.rs`
```rust
#![deny(missing_docs)]
#![deny(missing_debug_implementations)]
#![warn(clippy::must_use_candidate)]
#![cfg_attr(docsrs, feature(doc_auto_cfg))]
```
to take most benefits from docs' newest features (imo);
- [x] Create multiple examples in a new `logos/examples` directory: https://github.com/maciejhirsz/logos/pull/300
  - [x] a basic parser;
  - [x] a parser with regex groups;
  - [x] a JSON (or equivalent widely used format) parser;
  - [x] and any other idea.
so that they (1) will be tested, so it increases the coverage and (2) they will be documented as examples in the docs thanks to `-Zrustdoc-scrape-examples` option;
- [ ] Document each and every public function / attribute in the main repo (quite easy with Clippy's lints);
- [ ] Create some cookbook pages (similar to what [Clap does](https://docs.rs/clap/latest/clap/_derive/_tutorial/index.html#) with its `_tutorial` module) to further explain:
  - [ ] the internal Regex rules (what is possible and what is not);
  - [ ] the derive macro attributes;
  - [ ] or anything that solves issues (e.g., #124 or #214).
- [ ] This might not be pure documentation, but adding one or two [benchmarks](https://github.com/bheisler/criterion.rs) in some `logos/benches` directory can be a good idea imo https://github.com/maciejhirsz/logos/pull/301;
- [ ] Same as above, but with [fuzzing](https://github.com/rust-fuzz/cargo-fuzz)?

> NOTE: this is not an exhaustive list, and very important points may be missing. Also, some of the ideas I have listed might not be important for the near feature. Feel free to give your opinion below!

If @maciejhirsz agrees with any of those, I'd love to make some PR to help with it. I deeply think that this is a long process, that must take place in parallel to the code refactoring mentioned in [v0.13](https://github.com/maciejhirsz/logos/releases/tag/v0.13) or #291.

**Comment by maciejhirsz** [comment]
My go to still would be to make an mdbook akin to [serde](https://serde.rs). Proc macros are hard to document properly in standard Rust docs.

Also worth bringing up old issues about this, like #133.

**Comment by jeertmans** [comment]
Yes maybe using mdbook could replace the « _tutorial » module that is used for Clap (in my example). But I think having a well documented code + some examples is still a good idea. On top of that, you could include already existing example files in the book.
